rmw_zenoh_cpp: Include algorithm for std::find_if (#723) (#725)
src/detail/graph_cache.cpp:355:36: error: 'find_if' is not a member of 'std'; did you mean 'find'?


(cherry picked from commit 2ca58518d12e0344e15193c6a389b0bb3a108543)

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>
Co-authored-by: Jan Vermaete <jan.vermaete@gmail.com>